### ISSUE TITLE
Helper example

### ISSUE THREAD

**Issue by barrystaes** [webpack/items-store#7]
I would like to learn how to store multiple keys per item in `items-store`. In the introduction i read that i could use helpers to this end, but was not able to find documentation or examples that showed me how.

Documentation on helpers would be most welcome, notably an example CRUD implementation for items with a few fields, perhaps something like a PeoplePage in `react-starter` ?

**Comment by barrystaes** [comment]
FWIW;

At first the single-value per item scared me away and i briefly dabbed with Flummox. But to no avail .. for some reason i only found `GET` docs and examples.

I now realize that many Flux implementations do not offer the functionality that comes with `items-store`. Especially since the newer version. For sake of simplicity i already decided to overwrite these fields all at once, so basically could be treating them as a keyed array and just use `items-store`. And i imagine its also what items-store helpers do, but i wonder how i should use them, or what they (can) do exactly.

**Comment by sokra** [comment]
> I would like to learn how to store multiple keys per item in items-store.

Do I understand it correctly when I say i. e. a todo item with `text` and `done`?

**Comment by barrystaes** [comment]
Yes that would be a good example.

**Comment by sokra** [comment]
I've done some major refactoring to react-starter and it includes more (simpler) examples now i. e. to TodoItem now has `text` and `done`.

**Comment by barrystaes** [comment]
Just took a look at it. I expected an explicit `text` and `done` field in https://github.com/webpack/react-starter/blob/master/app/store-helpers/Todo.js but apparently there is no need for the store to know what it is storing. (i did not expect that)

For fun/demo, i tried adding a memo field:
https://github.com/barrystaes/react-starter/commit/b87892e04e40f3b60bbc8bbfd4174e553d7eac12
Its amazingly simple.

If  you where to do any validation of store data -clientside- i guess that the correct place to do that would be in a function just before mutating the store? (versus inside the store)

**Comment by sokra** [comment]
Yes, similar to a document db you can store any object. (Propably wise to use a document db on server too.)

In addition to server side validation you can do validation in:

* `app/mainStoresDescriptions` with `applyUpdate` where you have access to the complete item data after applying an update (throw an error, catch it in the container, which issues the action).
* `app/actions` where you can listen to an action and throw an error when the action is invalid (catch it in the container too)

Server side error (i. e. validation errors) can be handled with `applyNewError`. The default sets the item data to `null` and the item info `error` property to the error.

**Comment by barrystaes** [comment]
@sokra I do not understand why, but `this.state===null` inside `render()` in any Page..
